const fieldsKeys: string[] = [
    "Language - C#",
    "Language - Ruby",
    "Language - Python",
    "Language - JavaScript",
    "Language - Java",
    "Language - SQL",
    "Language - TypeScript",
    "Language - GraphQL",
    "Language - HTML",
    "Language - CSS/SCSS",
    "Language - Swift",
    "Language - C++",
    "Framework - Laravel",
    "Framework - ReactJS",
    "Framework - D3",
    "Framework - WebGL / Three.js",
    "Framework - Vue",
    "Framework - Angular",
    "Framework - Next.js",
    "Framework - React Native",
    "Framework - Flutter",
    "Framework - Tailwind",
    "Framework - Highcharts / Chart.js",
    "Framework - NodeJS",
    "Platform - Drupal",
    "Platform - WordPress Classic",
    "Platform - WordPress Gutenberg",
    "Platform - Contentful",
    "Platform - AEM",
    "Platform - Kentico",
    "Platform - Umbraco",
    "Platform - CraftCMS",
    "Platform - Shopify",
    "Platform - Yext",
    "Platform - Sanity.io",
    "Platform - Azure",
    "Platform - AWS",
    "Integration - Authentication / Authorization (Auth0, Cognito, Okta)",
    "Integration - Search (SOLR, Elasticsearch, Algolia)",
    "Integration - A/B Testing (Optimizely)",
    "Integration - Marketo",
    "Integration - Google Tag Manager",
    "Integration - Google Analytics",
    "Integration - Adobe Analytics",
    "Tool - Storybook",
    "Tool - Playwright",
    "Tool - Jest",
    "Tool - Yarn",
    "Tool - Composer",
    "Tool - Maven",
    "Skill - Content Migration",
    "Skill - Headless Architecture",
    "Skill - API Development",
    "Skill - A11y Implementation/Validation",
    "Skill - Performance Testing",
    "Skill - Security Testing",
    "Skill - Unit Testing",
    "Skill - Integration Testing",
    "Skill - Database Administration",
    "Skill - Content Modeling",
    "Skill - Figma",
    "Skill - Automated Content Translation",
    "Skill - Domain-driven Design",
    "Skill - SOA / Microservices",
    "Skill - Data Workflows (ETL/ELT)",
    "Skill - DevOps (Infrastructure)",
    "Skill - DevOps (Build and Developer Experience)",
    "Skill - Project Managment Tools (JIRA, et. al)",
    "Skill - Version Control (Git, SVN, CVS, Perforce, Mercurial)",
    "Skill - Observability (Datadog, Splunk, etc)",
    "Skill - Messaging oriented middleware (Mulesoft, kafka, SQS)",
    "Language - PHP",
    "Tool - Postman",
    "Platform - Django",
    "Language - Objective C",
   ];

export default fieldsKeys;
